blog/urls.py
from django.urls import include, path
from .views import (
    PostListView,
    PostDetailView,
    # PostCreateView,
    PostCreateUnderSpaceView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    FavouritesView,
    LikePostView,
    WikidataEntityAutocompleteView,
    generate_preview,
    posts_of_following_profiles,
)
from . import views

urlpatterns = [
    path("", PostListView.as_view(), name="blog-home"),
    path("myspace", posts_of_following_profiles, name="following-posts"),
    path("user/<str:username>", UserPostListView.as_view(), name="user-posts"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("post/<int:pk>", FavouritesView, name="post-favourites"),
    path("favouriteposts", views.favourite_posts, name="favourite-posts"),
    path("like_post/", LikePostView.as_view(), name="like_post"),
    path("filtertags/<int:pk>", views.filter_tags, name="filter-tags"),
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    path(
        "post/<int:space_id>/new/",
        PostCreateUnderSpaceView.as_view(),
        name="post-create-under-space",
    ),
    path("post/<int:pk>/update", PostUpdateView.as_view(), name="post-update"),
    path("post/<int:pk>/delete", PostDeleteView.as_view(), name="post-delete"),
    path("post/preview", generate_preview, name="post-preview"),
    path("about/", views.about, name="blog-about"),
    path(
        "wikidataentity-autocomplete/",
        WikidataEntityAutocompleteView.as_view(),
        name="wikidataentity-autocomplete",
    ),
    # path(
    #     "wikidatasubtype-autocomplete/",
    #     WikidataSubtypeAutocompleteView.as_view(),
    #     name="wikidatasubtype-autocomplete",
    # ),
]

django_project/urls.py
# django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('spaces/', include("spaces.urls")),
    path('profiles/', include("users.urls")),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spaces/urls.py
from django.urls import path
from .views import (
    SpaceListView,
    SpaceDetailView,
    SpaceCreateView,
    SpaceUpdateView,
    SpaceDeleteView,
    JoinSpaceView,
    MembersListView,
    ChangeMemberRoleView,
    search,
    user_posts,
    recommend_spaces,
)
# below are paths
urlpatterns = [
    path('', SpaceListView.as_view(), name='spaces-home'),
    path('<int:pk>/', SpaceDetailView.as_view(), name='space-detail'),
    path('<int:pk>/join', JoinSpaceView, name='join-space'),
    path('new/', SpaceCreateView.as_view(), name='space-create'),
    path('<int:pk>/update/', SpaceUpdateView.as_view(), name='space-update'),
    path('<int:pk>/delete/', SpaceDeleteView.as_view(), name='space-delete'),
    path('spaces/<int:pk>/members/', MembersListView.as_view(), name='members-list'),
    path('spaces/memberships/<int:membership_id>/change_member_role/', ChangeMemberRoleView.as_view(), name='change-member-role'),
    path('search/', search, name='search'),
    path('user/<str:username>/', user_posts, name='user_posts'),
    path('recommendations/', recommend_spaces, name='recommendations'),
]

spaces/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from users.models import Category


class Space(models.Model):

    PUBLIC = 'public'
    PRIVATE = 'private'

    POLICY_CHOICES = [
        (PUBLIC, 'Public'),
        (PRIVATE, 'Private'),
    ]

    category = models.ForeignKey(Category, related_name='single_category_spaces', on_delete=models.CASCADE, blank=True)
    categories = models.ManyToManyField(Category, related_name='multiple_categories_spaces')
    name = models.CharField(max_length = 100, unique=True)
    description = models.TextField(max_length = 500)
    date_created = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owned_spaces')
    policy = models.CharField(max_length=10, choices=POLICY_CHOICES, default=PUBLIC)
    members = models.ManyToManyField(User, through='SpaceMembership', related_name='spaces', blank=True)
    image = models.ImageField(default='space_default.jpg', upload_to='space_pics')



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('space-detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-date_created',)




class SpaceMembership(models.Model):
    OWNER = 'owner'
    BASIC_MEMBER = 'basic_member'
    PRO_MEMBER = 'pro_member'
    MODERATOR = 'moderator'

    ROLE_CHOICES = [
        (OWNER, 'Owner'),
        (BASIC_MEMBER, 'Basic Member'),
        (PRO_MEMBER, 'Pro Member'),
        (MODERATOR, 'Moderator'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    space = models.ForeignKey(Space, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=BASIC_MEMBER)

    def is_owner(self):
        return self.role == SpaceMembership.OWNER

    def is_moderator(self):
        return self.role == SpaceMembership.MODERATOR

    def is_pro_member(self):
        return self.role == SpaceMembership.PRO_MEMBER

    def is_basic_member(self):
        return self.role == SpaceMembership.BASIC_MEMBER


    class Meta:
        unique_together = ('user', 'space')

class PrivateSpaceRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    space = models.ForeignKey(Space, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

spaces/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from users.models import Profile, Category
import requests
from bs4 import BeautifulSoup
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from itertools import chain
from django.db.models import Q, Avg
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Space, SpaceMembership
from blog.models import Post
from django.views import View
from django.db.models import Q

from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import SpaceMembership, PrivateSpaceRequest
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from users import forms



def home(request):
    context = {
        'spaces': Space.objects.all()
    }
    return render(request, 'spaces/space_list.html', context)


class SpaceListView(ListView):
    model = Space
    template_name = 'spaces/space_list.html'
    context_object_name = 'spaces'
    ordering = ['-date_created']

#    def get_queryset(self):
#        user = self.request.user
#        user_categories = user.profile.categories.all()
#        return Space.objects.filter(category__in=user_categories).order_by('-date_created')


# class MySpacesListView(ListView):
#     model = Space
#     template_name = 'space/spaces.html'
#     context_object_name = 'spaces'
#     ordering = ['-date_created']

#     def get_queryset(self):
#         user = get_object_or_404(User, username=self.kwargs.get('username'))
#         # user_membership = SpaceMembership.objects.filter(user=request.user, space=space).first()
#         return Space.objects.filter(author=user, ).order_by('-date_created')

class SpaceDetailView(LoginRequiredMixin, DetailView):
    model = Space

    def get_filtered_posts(self):
        viewed_space = get_object_or_404(Space, id=self.kwargs['pk'])

        if self.request.user.is_authenticated:
            return Post.objects.filter(space=viewed_space).filter(
                Q(policy=Post.PUBLIC) | (
                    Q(policy=Post.PRIVATE) & Q(author=self.request.user))
            ).order_by('-date_posted')
        return Post.objects.filter(space=viewed_space, policy=Post.PUBLIC).order_by('-date_posted')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        # Variable showing if the user has authority to approve private space join requests
        approve_join = False
        # Variable showing if the user is member of the space
        is_member = False
        # Variable showing if the user is waiting to be approved to the private space
        is_pending = False
        # Variable showing is the user has authotiy to create a post under space
        is_writer = False

        # If the user is in the current spaces member list, then it is already a member
        viewed_space = get_object_or_404(Space, id=self.kwargs['pk'])
        if self.request.user in viewed_space.members.all():
            is_member = True
        # Variable showing if the viewed space is a public space
        is_public_space = False
        if viewed_space.policy == 'public':
            is_public_space = True

        # If any of the pending requests for the current space belong to the user, then it is waiting for approval
        results = PrivateSpaceRequest.objects.filter(
            space=viewed_space.id).all()
        for result in results:
            if result.user == self.request.user:
                is_pending = True

        # Initially, set user role to "not a member"
        xd = "not_a_member"
        # If the user is member of the viewed space, assign its role to the xd variable
        if SpaceMembership.objects.filter(space=viewed_space, user=self.request.user):
            xd = SpaceMembership.objects.filter(space=viewed_space,
                                                user=self.request.user).get().role

        # If the viewed space is a public space, then any member has write (creating post) authority
        if viewed_space.policy == 'public':
            if xd != 'not_a_member':
                is_writer = True
        # If the viewed space is private, then pro member and higher ranks have write authority
        else:
            if xd not in ["basic_member", "not_a_member"]:
                is_writer = True

        # If the role is owner or moderator, then the user has authority to approve join requests for provate spaces
        if xd in ["owner", "moderator"]:
            approve_join = True

        context["is_member"] = is_member
        context["is_writer"] = is_writer
        context['posts'] = self.get_filtered_posts()
        context['private_space_requests'] = PrivateSpaceRequest.objects.filter(
            space=viewed_space.id)
        context["is_pending"] = is_pending
        context["approve_join"] = approve_join
        context["is_public_space"] = is_public_space

        print(context)
        return context


class SpaceCreateView(LoginRequiredMixin, CreateView):
    model = Space
    fields = ['name', 'description', 'policy', 'image', 'category']

    def form_valid(self, form):
        form.instance.owner = self.request.user

        # Create a new category if the new_category field is not empty
        new_category = self.request.POST.get('new_category', '').strip()
        if new_category:
            category, _ = Category.objects.get_or_create(name=new_category)
            form.instance.category = category
            self.request.user.profile.categories.add(category)  # Add the new category to the user's profile categories

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class SpaceUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Space
    fields = ['name', 'description', 'policy', 'image', 'category']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        space = self.get_object()
        if self.request.user == space.owner:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class SpaceDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Space
    success_url = '/'

    def test_func(self):
        space = self.get_object()
        if self.request.user == space.owner:
            return True
        return False


def JoinSpaceView(request, pk):
    if request.method == 'POST':
        if request.POST.get('space_id'):
            space = get_object_or_404(Space, id=request.POST.get('space_id'))
            # If the user is already a member of the space, remove user from the space (leave request)
            if space.members.filter(id=request.user.id).exists():
                # If the space is private, delete user's posts from the space when leaving
                if space.policy == 'private':
                    # Get all the posts of the user in the current space
                    user_posts = Post.objects.filter(
                        space=space, author=request.user)
                    # Delete each post of the user
                    for each_post in user_posts:
                        each_post.delete()

                # If the space is public, keep the posts (do nothing)

                # Remove the user from space's member list
                space.members.remove(request.user.id)
            else:
                if space.policy == 'public':
                    space.members.add(request.user.id)
                else:
                    psr = PrivateSpaceRequest()
                    psr.user = request.user
                    psr.space = space
                    psr.save()
        else:
            space = get_object_or_404(Space, id=pk)
            if request.POST.get("approved"):
                space.members.add(request.POST.get("approved"))
                PrivateSpaceRequest.objects.get(
                    user_id=request.POST.get("approved")).delete()
            elif request.POST.get("declined"):
                PrivateSpaceRequest.objects.get(
                    user_id=request.POST.get("declined")).delete()
    return HttpResponseRedirect(reverse('space-detail', args=[str(pk)]))

# spaces/views.py


class MembersListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = SpaceMembership
    context_object_name = 'memberships'
    template_name = 'spaces/space_members.html'

    def get_queryset(self):
        space = get_object_or_404(Space, id=self.kwargs['pk'])
        memberships = SpaceMembership.objects.filter(
            space=space).exclude(user=space.owner).select_related('user')

        # Get or create an owner_membership for the owner and add it to the list of memberships
        owner_membership, _ = SpaceMembership.objects.get_or_create(user=space.owner, space=space,
                                                                    defaults={'role': 'owner'})
        memberships_with_owner = [owner_membership] + list(memberships)

        return memberships_with_owner

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        space = self.get_space()
        context['user_membership'] = get_object_or_404(
            SpaceMembership, user=self.request.user, space=space)

spaces/templates/spaces/recommendations.html
{% extends "blog/base.html" %}
{% block content %}
  <h1>Recommended Spaces</h1>
  {% for space in spaces %}
    <article class="media content-section">
      <h2><a class="article-title" href="{% url 'space-detail' space.id %}">{{ space.name }}</a></h2>
    </article>
  {% endfor %}
{% endblock content %}

spaces/templates/spaces/search.html
<!-- spaces/templates/spaces/search.html -->
{% extends "blog/base.html" %}
{% block content %}
    <h2>Search Results</h2>

    <h3>Spaces</h3>
    {% if spaces %}
        <table>
            <tr>
                <th>Space</th>
                <th>Creator</th>
            </tr>
        {% for space in spaces %}
            <tr>
                <td><a href="{% url 'space-detail' space.id %}">{{ space.name }}</a></td>
		        <td><a href="{% url 'user_posts' space.owner.username %}">{{ space.owner.username }}</a></td>
		    </tr>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No spaces found.</p>
    {% endif %}

    <h3>Posts</h3>
    {% if posts %}
        <table>
            <tr>
                <th>Post</th>
                <th>Author</th>
            </tr>
        {% for post in posts %}
            <tr>
                <td><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></td>
                <td><a href="{% url 'user_posts' post.author.username %}">{{ post.author.username }}</a></td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No posts found.</p>
    {% endif %}
{% endblock %}

spaces/templates/spaces/space_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Delete the Space</legend>
          <h2>Want to delete "{{ object.name }}"?</h2>
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-danger" type="submit">Yes, sure.</button>
          <a class="btn btn-outline-secondary" href="{% url 'space-detail' object.id %}">No</a>
        </div>
      </form>
    </div>
{% endblock content %}

spaces/templates/spaces/space_detail.html
{% extends "blog/base.html" %} {% block content %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ object.image.url }}" />
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'user-posts' object.owner.username %}"
        >{{ object.owner }}</a
      >
      <small class="text-muted">{{ object.date_created|date:"F d, Y" }}</small>
    <br>
    <div>
      {% if object.owner == user or is_member%}
	      <a
	        class="btn btn-info btn-sm mt-1 mb-1"
	        href="{% url 'members-list' object.id %}"
	        >View Members</a
	      >
      {% endif %} {% if object.owner == user %}

	        <a
	          class="btn btn-secondary btn-sm mt-1 mb-1"
	          href="{% url 'space-update' object.id %}"
	          >Update the Space</a
	        >
	        <a
	          class="btn btn-danger btn-sm mt-1 mb-1"
	          href="{% url 'space-delete' object.id %}"
	          >Delete the Space</a
	        >
    </div>
      <form
        class=""
        action="{% url 'post-create-under-space' object.pk %}"
        method="POST"
      >
        {% csrf_token %}
        <button
          type="submit"
          ,
          name="space_id"
          ,
          value="{{ object.id }}"
          ,
          class="btn btn-primary"
        >
          Write a Post
        </button>
      </form>
      {% endif %} {% if user != object.owner %}
      <form
        class=""
        action="{% url 'post-create-under-space' object.pk %}"
        method="POST"
      >
        {% csrf_token %} {% if is_writer %}
        <button
          type="submit"
          ,
          name="space_id"
          ,
          value="{{ object.id }}"
          ,
          class="btn btn-primary"
        >
          Write a Post
        </button>
        {% endif %}
      </form>
      {% endif %} {% if user != object.owner %}
      <form class="" action="{% url 'join-space' object.pk %}" method="POST">
        {% csrf_token %} {% if is_member %}
        <button
          type="submit"
          ,
          onclick="return confirm('Are you sure to leave?')"
          name="space_id"
          ,
          value="{{ object.id }}"
          ,
          class="btn btn-secondary"
        >
          Leave
        </button>
        {% else %} {% if is_pending %}
        <button
          type="submit"
          ,
          name="pending"
          ,
          class="btn btn-primary"
          disabled
        >
          Pending
        </button>
        {% else %}
        <button
          type="submit"
          ,
          name="space_id"
          ,
          value="{{ object.id }}"
          ,
          class="btn btn-primary"
        >
          Join
        </button>
        {% endif %} {% endif %}
      </form>
      {% endif %}
    </div>
    <div style="display: flex; flex-direction: column;">
        <div class="content-section">
	        <h2 class="article-title">{{ object.name }}</h2>
        </div>
        <div class="content-section">
	        <p class="article-content">{{ object.description }}</p>
        </div>
        <div class="content-section">
		   {% if object.category %}
			   <p><strong>Category:</strong> {{ object.category.name }}</p>
		   {% endif %}
	    </div>
    </div>
  </div>
</article>
{% if object.owner == user or is_member or is_public_space %}
<div class="container mt-4">
  <h2>Recent Posts</h2>
  {% for post in posts %}
  <article class="media content-section">
      <img
      class="rounded-circle article-img"
      src="{{ post.author.profile.image.url }}"
    />
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' post.author.username %}"
          >{{ post.author }}</a
        >
        <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
      </div>
      <h2>
        <a class="article-title" href="{% url 'post-detail' post.id %}"
          >{{ post.title }}</a
        >
      </h2>
      <p class="article-content">{{ post.content }}</p>
      <a class="article-link" href="{{ post.link }}" target="_blank"
        >{{ post.link }}</a
      >
      <div>
        {% for tag in post.tags.all %}
  <a href="{% url 'filter-tags' tag.id %}" class="badge badge-success">
    {{ tag.name }}
  </a>
  {% endfor %}
  </div> <!-- Move the closing endif tag here -->

  {% if post.image != "post_default.jpg" %}
   <img style="width: 100%;" src="{{ post.image.url }}" />
  {% endif %}

    </div>
    <div>
      {% if is_member and membership.role == "moderator" %}
      <form method="POST" action="{% url 'moderate-post' post.id %}">
        {% csrf_token %}
        <button type="submit" name="action" value="approve">Approve</button>
        <button type="submit" name="action" value="reject">Reject</button>
        <button type="submit" name="action" value="remove">Remove</button>
      </form>
      {% endif %}
    </div>
  </article>
  {% empty %}
  <p>No posts in this space yet.</p>
  {% endfor %}
</div>
{% endif %} {% endblock content %} {% block content2 %}
<div class="content-section">
  {% if object.owner == user or approve_join == True %}
  <form class="" action="{% url 'join-space' object.pk %}" method="POST">
    {% csrf_token %} {% for psr in private_space_requests %}
    <div>
      <a class="mr-2">{{ psr.user }}</a>
      <button
        type="submit"
        ,
        name="approved"
        ,
        value="{{ psr.user_id }}"
        ,
        class="btn btn-primary"
        ,
        style="background-color: green"
      >
        Onayla
      </button>
      <button
        type="submit"
        ,
        name="declined"
        ,
        value="{{ psr.user_id }}"
        ,
        class="btn btn-primary"
        ,
        style="background-color: red"
      >
        Reddet
      </button>
    </div>
    {% endfor %}
  </form>
  {% endif %}
</div>
{% endblock content2 %}

spaces/templates/spaces/space_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="content-section">
    <form method="POST" enctype="multipart/form-data" onsubmit="return validateForm();">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Create a Space</legend>
        {{ form|crispy }}
      </fieldset>

      <div class="form-group">
        <label for="new_category">New Category:</label>
        <input type="text" class="form-control" id="new_category" name="new_category" placeholder="Enter a new category if not found in the list">
      </div>

      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Submit</button>
      </div>
    </form>
  </div>

  <script>
    function validateForm() {
      const categorySelect = document.querySelector('#id_category');
      const newCategoryInput = document.querySelector('#new_category');

      if (!categorySelect.value && !newCategoryInput.value.trim()) {
        alert('Please select a category or enter a new category name.');
        return false;
      }
      return true;
    }
  </script>
{% endblock content %}

spaces/templates/spaces/space_list.html
{% extends "blog/base.html" %}
{% block content %}
  {% for space in spaces %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ space.image.url }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'user-posts' space.owner.username %}">{{ space.owner }}</a>
          <small class="text-muted">{{ space.date_created|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'space-detail' space.id %}">{{ space.name }}</a></h2>
        <p class="article-content">{{ space.description }}</p>
      </div>
    </article>
  {% endfor %}
{% endblock content %}

spaces/templates/spaces/space_members.html
<!-- space/members.html -->
{% extends "blog/base.html" %}

{% block content %}
  <h2 class="mb-4">Members</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Username</th>
        <th scope="col">Role</th>
        <th scope="col">Change Role</th>
        {% if user_membership.is_owner or user_membership.is_moderator%}
        <th scope="col">Remove</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for membership in memberships %}
        <tr>
          <td>{{ membership.user }}</td>
          <td>{{ membership.get_role_display }}</td>

          <td>
            {% if user_membership.is_owner %}
              {% if membership.role != 'owner' %}
                <form method="POST" action="{% url 'change-member-role' membership.id %}">
                  {% csrf_token %}
                  <select name="new_role" onchange="this.form.submit();">
                    <option value="basic_member" {% if membership.role == 'basic_member' %}selected{% endif %}>Basic Member</option>
                    <option value="pro_member" {% if membership.role == 'pro_member' %}selected{% endif %}>Pro Member</option>
                    <option value="moderator" {% if membership.role == 'moderator' %}selected{% endif %}>Moderator</option>
                  </select>
                </form>
              {% endif %}

            {% elif user_membership.is_moderator %}
              {% if membership.role == 'basic_member' or membership.role == 'pro_member' %}
                <form method="POST" action="{% url 'change-member-role' membership.id %}">
                  {% csrf_token %}
                  <select name="new_role" onchange="this.form.submit();">
                    <option value="basic_member" {% if membership.role == 'basic_member' %}selected{% endif %}>Basic Member</option>
                    <option value="pro_member" {% if membership.role == 'pro_member' %}selected{% endif %}>Pro Member</option>
                    <option value="moderator" {% if membership.role == 'moderator' %}selected{% endif %}>Moderator</option>
                  </select>
                </form>
              {% else %}
                <span>{{ membership.get_role_display }}</span>
              {% endif %}

            {% elif user_membership.is_pro_member %}
              {% if membership.role == 'basic_member' %}
                <form method="POST" action="{% url 'change-member-role' membership.id %}">
                  {% csrf_token %}
                  <select name="new_role" onchange="this.form.submit();">
                    <option value="basic_member" {% if membership.role == 'basic_member' %}selected{% endif %}>Basic Member</option>
                    <option value="pro_member" {% if membership.role == 'pro_member' %}selected{% endif %}>Pro Member</option>
                  </select>
                </form>
              {% else %}
                <span>{{ membership.get_role_display }}</span>
              {% endif %}

            {% else %}
              <span>{{ membership.get_role_display }}</span>
            {% endif %}
            
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

spaces/templates/spaces/space_tags.html
from django import template

register = template.Library()

@register.simple_tag
def can_change_role(request_user, membership):
    if request_user == membership.space.owner:
        return True
    if membership.user == request_user:
        return True
    if membership.role in ['basic_member', 'pro_member'] and request_user in membership.space.moderators.all():
        return True
    return False

spaces/templates/spaces/user_posts.html
{% extends "blog/base.html" %}

{% block content %}

    <h2>{{ user.username }}'s Posts</h2>
    {% if posts %}
        <table>
            <tr>
                <th>Post</th>
                <th>Space</th>
            </tr>
        {% for post in posts %}
            <tr>
                <td>
                    <!-- Add a link to the post detail view -->
                    <a href="{% url 'post-detail' post.id %}">{{ post.title }}</a>
                </td>
                <td>
                    <!-- Add a link to the space detail view -->
                    <a href="{% url 'space-detail' post.space.id %}">{{ post.space.name }}</a>
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No posts found.</p>
    {% endif %}
{% endblock %}