blog/urls.py
from django.urls import include, path
from .views import (
    PostListView,
    PostDetailView,
    # PostCreateView,
    PostCreateUnderSpaceView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    FavouritesView,
    LikePostView,
    WikidataEntityAutocompleteView,
    generate_preview,
    posts_of_following_profiles,
)
from . import views

urlpatterns = [
    path("", PostListView.as_view(), name="blog-home"),
    path("myspace", posts_of_following_profiles, name="following-posts"),
    path("user/<str:username>", UserPostListView.as_view(), name="user-posts"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("post/<int:pk>", FavouritesView, name="post-favourites"),
    path("favouriteposts", views.favourite_posts, name="favourite-posts"),
    path("like_post/", LikePostView.as_view(), name="like_post"),
    path("filtertags/<int:pk>", views.filter_tags, name="filter-tags"),
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    path(
        "post/<int:space_id>/new/",
        PostCreateUnderSpaceView.as_view(),
        name="post-create-under-space",
    ),
    path("post/<int:pk>/update", PostUpdateView.as_view(), name="post-update"),
    path("post/<int:pk>/delete", PostDeleteView.as_view(), name="post-delete"),
    path("post/preview", generate_preview, name="post-preview"),
    path("about/", views.about, name="blog-about"),
    path(
        "wikidataentity-autocomplete/",
        WikidataEntityAutocompleteView.as_view(),
        name="wikidataentity-autocomplete",
    ),
    # path(
    #     "wikidatasubtype-autocomplete/",
    #     WikidataSubtypeAutocompleteView.as_view(),
    #     name="wikidatasubtype-autocomplete",
    # ),
]

django_project/urls.py
# django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('spaces/', include("spaces.urls")),
    path('profiles/', include("users.urls")),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import ProfileListView, ProfileDetailView, follow_unfollow_profile, recommend_users


app_name = 'profiles'



urlpatterns = [
    path('list/', ProfileListView.as_view(), name='profile-list'),
    path('switch_follow/', follow_unfollow_profile, name='follow-unfollow'),
    path('list/<pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('recommendations/', recommend_users, name='user-recommendations'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from spaces.models import Space, SpaceMembership


class WikidataEntity(models.Model):
    entity_id = models.CharField(max_length=255, unique=True)
    label = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.label


# class WikidataSubtype(models.Model):
#     entity = models.ForeignKey(
#         WikidataEntity, related_name="subtypes", on_delete=models.CASCADE
#     )
#     subtype_id = models.CharField(max_length=255, unique=True)
#     label = models.CharField(max_length=255)

#     def __str__(self):
#         return self.label

class Post(models.Model):
    PUBLIC = "public"
    PRIVATE = "private"

    POLICY_CHOICES = [
        (PUBLIC, "Public"),
        (PRIVATE, "Private"),
    ]

    APPROVED = "approved"
    REJECTED = "rejected"
    PENDING = "pending"

    STATUS_CHOICES = [
        (APPROVED, "Approved"),
        (REJECTED, "Rejected"),
        (PENDING, "Pending"),
    ]

    policy = models.CharField(
        max_length=10, choices=POLICY_CHOICES, default=PUBLIC, blank=False
    )
    title = models.CharField(max_length=100, blank=False)
    content = models.TextField(max_length=500, blank=False)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    link = models.URLField(default="", blank=False)
    space = models.ForeignKey(
        Space, on_delete=models.CASCADE, related_name="posts", blank=True, null=True
    )
    favourites = models.ManyToManyField(User, related_name="favourites", blank=True)
    likes = models.ManyToManyField(User, related_name="liked_posts", blank=True)
    tags = TaggableManager(blank=True)
    wikitags = models.ManyToManyField(WikidataEntity, related_name='posts', blank=True)
    # wikisubtypes = models.ManyToManyField(WikidataSubtype, related_name='posts', blank=True)
    image = models.ImageField(
        default="post_default.jpg", upload_to="post_pics", blank=True
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=PENDING)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = ("-date_posted",)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=200)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.content[:20]}"

blog/forms.py
from django import forms
from django.forms import Textarea
from .models import Comment, Post, WikidataEntity


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            "content": Textarea(attrs={"rows": 3, "cols": 40}),
        }


class PostCreateUnderSpaceForm(forms.ModelForm):
    wikitags = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "Enter tags separated by commas"}),
    )

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "link",
            "tags",
            "policy",
            "image",
            "wikitags",
            # "wikisubtypes",
        ]
        widgets = {
            "content": Textarea(attrs={"rows": 3, "cols": 40}),
            "tags": forms.TextInput(
                attrs={"placeholder": "Enter tags separated by commas"}
            ),
            "image": forms.FileInput(),
            "link": forms.TextInput(attrs={"placeholder": "Enter link to article"}),
            "title": forms.TextInput(attrs={"placeholder": "Enter title"}),
            # "wikisubtypes": forms.TextInput(attrs={"id": "wikisubtypes-input"}),
        }

blog/views.py
from pyexpat.errors import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.views import View
from blog.wikidata import search_wikidata_entities

from users.models import Profile
from spaces.models import Space, SpaceMembership
import requests
from bs4 import BeautifulSoup
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from itertools import chain
from django.db.models import Q
from django.views.generic import (
    View,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from . import models
from .models import Post
from .forms import CommentForm, PostCreateUnderSpaceForm

from .models import WikidataEntity


def home(request):
    context = {"posts": Post.objects.all()}
    return render(request, "blog/home.html", context)


class PostListView(ListView):
    model = Post
    template_name = "blog/home.html"
    context_object_name = "posts"
    ordering = ["-date_posted"]
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Post.objects.filter(
                Q(policy=Post.PUBLIC)
                | (Q(policy=Post.PRIVATE) & Q(author=self.request.user))
            ).order_by("-date_posted")
        return Post.objects.filter(policy=Post.PUBLIC).order_by("-date_posted")


class UserPostListView(ListView):
    model = Post
    template_name = "blog/user_posts.html"
    context_object_name = "posts"
    ordering = ["-date_posted"]
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get("username"))
        return Post.objects.filter(author=user, policy=Post.PUBLIC).order_by(
            "-date_posted"
        )


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        viewed_post = get_object_or_404(Post, id=self.kwargs["pk"])
        if viewed_post.favourites.filter(id=self.request.user.id).exists():
            save = True
        else:
            save = False
        context["save"] = save
        context["comment_form"] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.get_object()
            comment.user = request.user
            comment.save()
            return redirect("post-detail", pk=self.get_object().pk)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post

    fields = ["title", "content", "link", "tags", "policy", "image"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostCreateUnderSpaceView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreateUnderSpaceForm

    def get_space(self):
        space_id = self.kwargs.get("space_id")
        space = get_object_or_404(Space, id=space_id)
        return space

    def dispatch(self, request, *args, **kwargs):
        space = self.get_space()
        user_membership = SpaceMembership.objects.filter(
            user=request.user, space=space
        ).first()
        user_existence = False

        if (
            SpaceMembership.objects.filter(user=request.user, space=space).exists()
            or request.user == space.owner
        ):
            user_existence = True

        if not user_existence:
            raise PermissionDenied(
                "You must be a member of this space to create a post."
            )

        if request.user != space.owner:
            if (
                space.policy == Space.PRIVATE
                and user_membership.role == SpaceMembership.BASIC_MEMBER
            ):
                raise PermissionDenied(
                    "You must be a Pro Member or Moderator in a private space to create a post."
                )

        return super().dispatch(request, *args, **kwargs)

    def check_duplicate_link(self, form):
        link = form.cleaned_data.get("link")
        space = self.get_space()

        duplicate_post = Post.objects.filter(space=space, link=link).first()
        if duplicate_post:
            context = self.get_context_data()
            context["duplicate_post"] = duplicate_post
            context["form"] = form
            return self.render_to_response(context)
        return None

    def form_valid(self, form):
        if "deny" in self.request.POST:
            return HttpResponseRedirect(reverse("blog-home"))
        if "confirm" not in self.request.POST:
            duplicate_response = self.check_duplicate_link(form)
            if duplicate_response:
                return duplicate_response

        form.instance.author = self.request.user
        form.instance.space = self.get_space()
        post = form.save()

        wikitags = form.cleaned_data["wikitags"].split(",")
        for tag in wikitags:
            tag = tag.strip()
            if tag:  # avoid empty tags
                try:
                    entity = WikidataEntity.objects.get(label=tag)
                    post.wikitags.add(entity)
                except WikidataEntity.DoesNotExist:
                    # Handle the case when the tag does not exist in the database
                    messages.error(self.request, f"Tag {tag} does not exist.")

        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostCreateUnderSpaceForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = form.save()

        post.wikitags.clear()

        wikitags = form.cleaned_data["wikitags"].split(",")
        for tag in wikitags:
            tag = tag.strip()
            if tag:  # avoid empty tags
                try:
                    entity = WikidataEntity.objects.get(id=tag)
                    post.wikitags.add(entity)                    
                except WikidataEntity.DoesNotExist:
                    # Handle the case when the tag does not exist in the database
                    messages.error(self.request, f"Tag {tag} does not exist.")
        post.save()
        
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = "/"

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, "blog/about.html", {"title": "About"})


def get_title(html):
    """Scrape page title."""
    title = None
    if html.title.string:
        title = html.title.string
    elif html.find("meta", property="og:title"):
        title = html.find("meta", property="og:title").get("content")
    elif html.find("meta", property="twitter:title"):
        title = html.find("meta", property="twitter:title").get("content")
    elif html.find("h1"):
        title = html.find("h1").string
    return title


def get_description(html):
    """Scrape page description."""
    description = None
    if html.find("meta", property="description"):
        description = html.find("meta", property="description").get("content")
    elif html.find("meta", property="og:description"):
        description = html.find("meta", property="og:description").get("content")
    elif html.find("meta", property="twitter:description"):
        description = html.find("meta", property="twitter:description").get("content")
    elif html.find("p"):
        description = html.find("p").contents
    return description


def get_image(html):
    """Scrape share image."""
    image = None
    if html.find("meta", property="image"):
        image = html.find("meta", property="image").get("content")
    elif html.find("meta", property="og:image"):
        image = html.find("meta", property="og:image").get("content")
    elif html.find("meta", property="twitter:image"):
        image = html.find("meta", property="twitter:image").get("content")
    elif html.find("img", src=True):
        image = html.find_all("img").get("src")
    return image


def generate_preview(request):
    headers = {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET",
        "Access-Control-Allow-Headers": "Content-Type",
        "Access-Control-Max-Age": "3600",
        "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0",
    }

    url = request.GET.get("link")
    print(url)
    req = requests.get(url, headers)
    html = BeautifulSoup(req.content, "html.parser")
    meta_data = {
        "title": get_title(html),
        "description": get_description(html),
        "image": get_image(html),
    }

    print(meta_data)

    return JsonResponse(meta_data)


def posts_of_following_profiles(request):
    profile = Profile.objects.get(user=request.user)
    users = [user for user in profile.following.all()]
    posts = []
    paginate_by = 5
    qs = None
    for u in users:
        p = Post.objects.filter(author=u, policy=Post.PUBLIC)
        posts.append(p)
    my_posts = Post.objects.filter(author=request.user)
    posts.append(my_posts)
    if len(posts) > 0:
        qs = sorted(chain(*posts), reverse=True, key=lambda obj: obj.date_posted)
    return render(request, "blog/myspace.html", {"posts": qs})


def FavouritesView(request, pk):
    if request.method == "POST":

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About</h1>
    <a>ShareIt designed as a social media platform where users can create spaces,
      post content, and interact with each other. Users can join spaces based on their interests,
      create and share posts within those spaces, and follow other users.
      The platform offers features such as post recommendations, favorites, tags, search, user profiles,
      annotations.</a>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
    <script src="http://aehlke.github.io/tag-it/js/tag-it.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    {% comment %} <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    /> {% endcomment %}
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.7.2/font/bootstrap-icons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'blog/main.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/smoothness/jquery-ui.css" />
    <link rel="stylesheet" href="http://aehlke.github.io/tag-it/css/jquery.tagit.css" />

    {% comment %} <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css"
      integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/5v5zS4pJocDzODDp5pBs8e7Kw5qo1m7kmSV4/"
      crossorigin="anonymous"
    /> {% endcomment %}

    <link href="{% static 'autocomplete_light/select2.css' %}" rel="stylesheet">

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Your App Name{% endblock %}</title>
    <style>
      table {
        border-collapse: separate;
        border-spacing: 25px; /* Adjust this value to increase or decrease the spacing between columns */
      }

      table {
        border-collapse: separate;
        border-spacing: 20px; /* Adjust this value to increase or decrease the spacing between columns */
      }
    </style>
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home'%}">ShareIt</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggle"
            aria-controls="navbarToggle"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home'%}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog-about'%}"
                >About</a
              >
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <form
                method="get"
                action="{% url 'search' %}"
                onsubmit="return checkForm(this);"
              >
                <div class="input-group">
                  <div class="form-inline">
                    <input
                      type="text"
                      id="form1"
                      class="form-control"
                      name="q"
                      placeholder="Search"
                      aria-label="Search"
                    />
                  </div>
                  <button type="submit" class="btn btn-primary">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </form>
              <a class="nav-item nav-link" href="{% url 'following-posts' %}"
                >Followed Posts</a
              >
              <a class="nav-item nav-link" href="{% url 'space-create' %}"
                >Create a Space</a
              >
              <a class="nav-item nav-link" href="{% url 'profile' %}"
                >Profile</a
              >
              <a class="nav-item nav-link" href="{% url 'recommendations' %}"
                >Recommendations</a
              >
              <a
                class="nav-item nav-link"
                href="{% url 'profiles:profile-list' %}"
                >Users</a
              >
              <a class="nav-item nav-link" href="{% url 'spaces-home' %}"
                >Spaces</a
              >
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}"
                >Register</a
              >

              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %} {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
          {% endfor %} {% endif %} {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">{% block content2 %}{% endblock %}</div>
      </div>
    </main>
    {% comment %} <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script> {% endcomment %}
    {% comment %} <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script> {% endcomment %}
    {% comment %} <script src="{% static 'autocomplete_light/i18n/en.js' %}"></script> {% endcomment %}
  </body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Delete the Post</legend>
          <h2>Want to delete "{{ object.title }}"?</h2>
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-danger" type="submit">Yes, sure.</button>
          <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">No</a>
        </div>
      </form>
    </div>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %} {% load crispy_forms_filters %} {% load
crispy_forms_tags %} {% block content %}
<div class="content-section">
  {% if duplicate_post %}
  <div class="alert alert-warning" role="alert">
    A post with the same link already exists:
    <a href="{{ duplicate_post.get_absolute_url }}"
      >{{ duplicate_post.title }}</a
    >.
    <br />
    Are you sure you want to submit another post with the same link?
  </div>
  <form id="post-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Create a Post</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button type="submit" name="confirm" value="yes" class="btn btn-warning">
        Yes, submit anyway
      </button>
      <button
        style="background-color: #c19a6b"
        type="submit"
        name="deny"
        value="no"
        class="btn btn-warning"
      >
        No, do not submit
      </button>
    </div>
  </form>
  {% else %}
  <form id="post-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Create a Post</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit" id="submit-btn">
        Done
      </button>
    </div>
  </form>
  {% endif %}
</div>
<script>
  document
    .getElementById("submit-btn")
    .addEventListener("click", function (event) {
      event.preventDefault(); // Prevent the default form submission
      // Custom logic or validation can be added here
      // For example, you can check if the required fields are filled before submitting the form
      var titleInput = document.getElementById("id_title");
      var contentInput = document.getElementById("id_content");

      if (titleInput.value.trim() === "" || contentInput.value.trim() === "") {
        alert("Title and content fields cannot be empty.");
        return;
      }

      // Submit the form if all conditions are met
      document.getElementById("post-form").submit();
    });

    $(document).ready(function() {
        $("#id_wikitags").tagit({
            fieldName: "wikitags",
            singleField: true,
            autocomplete: {
                source: function(request, response) {
                    $.ajax({
                        url: "{% url 'wikidataentity-autocomplete' %}",
                        data: { term: request.term },
                        dataType: "json",
                        success: function(data) {
                            response($.map(data, function(item) {
                                return { label: 22, value: 22 };
                            }));
                        }
                    });
                },
                delay: 500,
                minLength: 2
            },
        });
    });



  {% comment %} $("#wikisubtypes-input").autocomplete({
    source: "{% url 'wikidatasubtype-autocomplete' %}",
    minLength: 2,
    select: function (event, ui) {
      event.preventDefault();
      $(this).val(ui.item.label);
      $("#id_wikisubtypes").val(ui.item.id);
    },
  }); {% endcomment %}
</script>
{% endblock content %}