blog/urls.py
from django.urls import include, path
from .views import (
    PostListView,
    PostDetailView,
    # PostCreateView,
    PostCreateUnderSpaceView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    FavouritesView,
    LikePostView,
    WikidataEntityAutocompleteView,
    generate_preview,
    posts_of_following_profiles,
)
from . import views

urlpatterns = [
    path("", PostListView.as_view(), name="blog-home"),
    path("myspace", posts_of_following_profiles, name="following-posts"),
    path("user/<str:username>", UserPostListView.as_view(), name="user-posts"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("post/<int:pk>", FavouritesView, name="post-favourites"),
    path("favouriteposts", views.favourite_posts, name="favourite-posts"),
    path("like_post/", LikePostView.as_view(), name="like_post"),
    path("filtertags/<int:pk>", views.filter_tags, name="filter-tags"),
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    path(
        "post/<int:space_id>/new/",
        PostCreateUnderSpaceView.as_view(),
        name="post-create-under-space",
    ),
    path("post/<int:pk>/update", PostUpdateView.as_view(), name="post-update"),
    path("post/<int:pk>/delete", PostDeleteView.as_view(), name="post-delete"),
    path("post/preview", generate_preview, name="post-preview"),
    path("about/", views.about, name="blog-about"),
    path(
        "wikidataentity-autocomplete/",
        WikidataEntityAutocompleteView.as_view(),
        name="wikidataentity-autocomplete",
    ),
    # path(
    #     "wikidatasubtype-autocomplete/",
    #     WikidataSubtypeAutocompleteView.as_view(),
    #     name="wikidatasubtype-autocomplete",
    # ),
]

django_project/urls.py
# django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('spaces/', include("spaces.urls")),
    path('profiles/', include("users.urls")),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import ProfileListView, ProfileDetailView, follow_unfollow_profile, recommend_users


app_name = 'profiles'



urlpatterns = [
    path('list/', ProfileListView.as_view(), name='profile-list'),
    path('switch_follow/', follow_unfollow_profile, name='follow-unfollow'),
    path('list/<pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('recommendations/', recommend_users, name='user-recommendations'),

]

users/models.py
from django.db import models
from django.db.models import Sum
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Count, Avg

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    following = models.ManyToManyField(User, related_name='following', blank=True)
    updated = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(default=timezone.now)
    categories = models.ManyToManyField(Category, related_name='categories', blank=True)



    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def profiles_posts(self):
        return self.post_set.all()

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import MultipleHiddenInput
from .models import Profile, Category


class UserUpdateForm(forms.ModelForm):
        email = forms.EmailField()

        class Meta:
            model = User
            fields = ['username', 'email']

# CATEGORIES = [
#     ('art', 'Art'),
#     ('baseball', 'Baseball'),
#     ('basketball', 'Basketball'),
#     ('business', 'Business'),
#     ('culture', 'Culture'),
#     ('economy', 'Economy'),
#     ('education', 'Education'),
#     ('entertainment', 'Entertainment'),
#     ('environment', 'Environment'),
#     ('earthquakes', 'Earthquakes'),
#     ('fashion', 'Fashion'),
#     ('food', 'Food'),
#     ('football', 'Football'),
#     ('games', 'Games'),
#     ('health', 'Health'),
#     ('history', 'History'),
#     ('hockey', 'Hockey'),
#     ('language', 'Language'),
#     ('literature', 'Literature'),
#     ('music', 'Music'),
#     ('nature', 'Nature'),
#     ('philosophy', 'Philosophy'),
#     ('politics', 'Politics'),
#     ('religion', 'Religion'),
#     ('science', 'Science'),
#     ('society', 'Society'),
#     ('software', 'Software'),
#     ('sports', 'Sports'),
#     ('technology', 'Technology'),
#     ('tennis', 'Tennis'),
#     ('travel', 'Travel'),
#     ('volleyball', 'Volleyball'),
# ]


class ProfileUpdateForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    custom_category = forms.CharField(
        max_length=100,
        required=False,
        help_text="Enter a new category name if you can't find it in the list above."
    )

    class Meta:
        model = Profile
        fields = ['image', 'categories', 'custom_category']

    def save(self, commit=True):
        profile = super(ProfileUpdateForm, self).save(commit=False)
        if commit:
            profile.save()
        selected_categories = self.cleaned_data.get('categories')
        custom_category_name = self.cleaned_data.get('custom_category')
        if custom_category_name:
            custom_category, created = Category.objects.get_or_create(name=custom_category_name)
            selected_categories = list(selected_categories) + [custom_category]
        profile.categories.set(selected_categories)
        return profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'categories']

    def clean(self):
        cleaned_data = super().clean()
        custom_categories = self.data.getlist('custom_categories')
        categories = cleaned_data.get('categories')
        if categories is None:
            categories = []
        else:
            categories = list(categories)

        for category_name in custom_categories:
            category, created = Category.objects.get_or_create(name=category_name)
            categories.append(category)
            cleaned_data['categories'] = categories
        return cleaned_data

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.save()
        categories = self.cleaned_data.get('categories')
        user.profile.categories.add(*categories)
        return user

users/views.py
from django.db.models import Count, Avg
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views import View

from blog.models import Post
from spaces.models import Space
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views.generic import ListView, DetailView
from .models import Profile, Category, User
# from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

def follow_unfollow_profile(request):
    if request.method == 'POST':
        my_profile = Profile.objects.get(user=request.user)
        pk = request.POST.get('profile_pk')
        obj = Profile.objects.get(pk=pk)
        if obj.user in my_profile.following.all():
            my_profile.following.remove(obj.user)
        else:
            my_profile.following.add(obj.user)
    return redirect('profiles:profile-list')

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            selected_categories = form.cleaned_data.get('categories')
            user.profile.categories.set(selected_categories)
            user.profile.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

class ProfileListView(ListView):
    model = Profile
    template_name = 'users/user_list.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        return Profile.objects.all().exclude(user=self.request.user)

class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'users/user_detail.html'

    def get_object(self, **kwargs):
        pk = self.kwargs.get('pk')
        view_profile = Profile.objects.get(pk=pk)
        return view_profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        view_profile = self.get_object()
        my_profile = Profile.objects.get(user=self.request.user)
        if view_profile.user in my_profile.following.all():
            follow = True
        else:
            follow = False
        context["follow"] = follow
        return context


def recommend_users(request):
    # Get the categories checked by the user
    selected_categories = request.user.profile.categories.all()

    # Filter spaces which have these categories
    users = Profile.objects.filter(categories__in=selected_categories)

    # For each space, get all posts and calculate the total posts' amount and average likes
    """relevant_users = []
    first_encounter = []
    for user in users:
        if user in first_encounter and user not in relevant_users and user.id != request.user.id:
            relevant_users.append(user)
        else:
            first_encounter.append(user)"""

    counts = {}
    relevant_users = []

    for user in users:
        counts[user] = counts.get(user, 0) + 1

        if counts[user] >= 2 and user not in relevant_users and user.id != request.user.id:
            relevant_users.append(user)

    # Pass the relevant spaces to the template
    return render(request, 'users/recommendations.html', {'users': relevant_users})

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Log In</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Login</button>
          <small class="text-muted ml-2">
            <a class="ml-2" href="{% url 'password_reset' %}">Forgot Password?</a>
          </small>
        </div>
      </form>
      <div class="border-top pt3">
        <small class="text-muted">
          You don't have an account?<a class="ml-2" href="{% url 'register' %}">Sign Up!</a>
        </small>
      </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
      <h2>You have logged out!</h2>
      <div class="border-top pt3">
        <small class="text-muted">
          Want to login back?<a class="ml-2" href="{% url 'login' %}">Log In</a>
        </small>
      </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Reset Password</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Submit Request</button>
        </div>
      </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}
      <div class="alert alert-info">
        Your password has been reset.
      </div>
      <a href="{% url 'login' %}">Log In Now</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Reset Password</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Confirm Reset</button>
        </div>
      </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}
      <div class="alert alert-info">
        Email has been sent to reset your password.
      </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Details</legend>
        {{ u_form|crispy }}
        {{ p_form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Save</button>
      </div>
    </form>
  </div>
{% endblock content %}

users/templates/users/recommendations.html
{% extends "blog/base.html" %}
{% block content %}
  <h1>Recommended Users</h1>
  {% for user in users %}
    <article class="media content-section">
      <h2><a class="article-title" href="{% url 'user-posts' user.user.username %}">{{ user.user.username }}</a></h2>
    </article>
  {% endfor %}
{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
            <div id="add-category-container">
                <input id="add-category-input" type="text" placeholder="Add a new category" />
                <button id="add-category-button" type="button">Add</button>
            </div>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
  </div>
  <script>
	document.addEventListener('DOMContentLoaded', function() {
	    const addCategoryButton = document.getElementById('add-category-button');
	    const addCategoryInput = document.getElementById('add-category-input');
	    const categoryContainer = document.querySelector(".form-group");

	    addCategoryButton.addEventListener('click', function() {
	        const newCategoryName = addCategoryInput.value.trim();
	        if (newCategoryName) {
	            const newCheckbox = document.createElement('input');
	            newCheckbox.type = 'checkbox';
	            newCheckbox.name = 'custom_categories';
	            newCheckbox.value = newCategoryName;
	            newCheckbox.checked = true;

	            const label = document.createElement('label');
	            label.textContent = newCategoryName;

	            const container = document.createElement('div');
	            container.appendChild(newCheckbox);
	            container.appendChild(label);

	            categoryContainer.insertBefore(container, addCategoryInput.parentElement);
                addCategoryInput.value = '';
	        }
	    });
	});
  </script>
{% endblock content %}

users/templates/users/user_detail.html
{% extends "blog/base.html" %}
{% block title %}
  <h1 class="mb-3">User Detail</h1>
{% endblock title %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.user.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' object.user.username %}">{{ object.user.username }}</a>
        <small class="text-muted">{{ object.created }}</small>
      </div>
      {% if follow %}
        <form class="" action="{% url 'profiles:follow-unfollow' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="profile_pk" value={{ object.pk }}>
          <button type="submit" name="button" class="btn btn-secondary">Unfollow</button>
        </form>
      {% else %}
        <form class="" action="{% url 'profiles:follow-unfollow' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="profile_pk" value={{ object.pk }}>
          <button type="submit" name="button" class="btn btn-primary">Follow</button>
        </form>
      {% endif %}

      <div class="">

      </div>
    </div>
  </article>
{% endblock content %}

users/templates/users/user_list.html
{% extends "blog/base.html" %}
{% block title %}
  <h1 class="mb-3">User List</h1>
{% endblock title %}
{% block content %}
  {% for profile in profiles %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ profile.user.profile.image.url }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'user-posts' profile.user.username %}">{{ profile.user.username }}</a>
          <small class="text-muted">{{ profile.created }}</small>
        </div>
        <a id="preview_link_btn{{ post.id }}" href="{% url 'profiles:profile-detail' profile.pk %}" class="btn btn-primary">Visit Profile</a>
      </div>
    </article>
  {% endfor %}
{% endblock content %}